version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: metamorphosis-zookeeper
    ports:
      - 2181:2181
    environment:
      JMX_OPTS: "-Djava.security.auth.login.config=/etc/kafka/server-jaas.conf"
    volumes:
      - ./server-jaas.conf:/etc/kafka/server-jaas.conf

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: metamorphosis-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9193:9193"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,SSL://localhost:9093,SASL_SSL://localhost:9193"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093,SASL_SSL://:9193"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SSL_KEYSTORE_LOCATION: "/certs/docker.kafka.server.keystore.jks"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/certs/docker.kafka.server.truststore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "nodesinek"
      KAFKA_SSL_KEY_PASSWORD: "nodesinek"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "nodesinek"
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: "SASL_SSL"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_JMX_OPTS: "-Djava.security.auth.login.config=/etc/kafka/server-jaas.conf"
    volumes:
      - /tmp/kafka-data/data:/data
      - /tmp/kafka-data/logs:/logs
      - ./server-jaas.conf:/etc/kafka/server-jaas.conf
      - ../../certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
